apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-node-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: Your_image_name #add your image name
          ports:
            - containerPort: 9600
          envFrom:
            - configMapRef:
                name: node-app-env
          volumeMounts:
            - name: credentials-volume
              mountPath: /usr/src/app/credentials.json
              subPath: credentials.json
      volumes:
        - name: credentials-volume
          secret:
            secretName: node-app-credentials
